apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}-svc 
  {{- if .Values.customLabels }} 
  labels: {{- toYaml .Values.customLabels | nindent 6 }} 
  {{- end }}
spec:
  type: {{.Values.service.type}}
  ports:
   {{- with .Values.service.nodePorts }}
   {{- toYaml . | nindent 6 }}
   {{- end }}
  selector:
    app: {{.Values.appName}}

